### ISSUE TITLE
[BUG] start command crash

### ISSUE THREAD

**Issue by pouyamiralayi** [galio-org/galio-starter-kit#1]
Hello there! i just cloned your kit and issued ``yarn run start`` the galio dashboard opened up in my browser but after some seconds it crashed. this is the cli output:
```
yarn run v1.19.1
$ expo start
Starting project at C:\Users\Admin\Documents\galio-starter-kit
Expo DevTools is running at http://localhost:19002
Opening DevTools in the browser... (press shift-d to disable)
Some of your project's dependencies are not compatible with currently installed expo package version:
 - react-native-svg - expected version range: ~9.9.2 - actual version installed: ^9.12.0
Your project may not work correctly until you install the correct versions of the packages.
To install the correct versions of these packages, please run: expo install [package-name ...]
error Invalid regular expression: /(.*\\__fixtures__\\.*|node_modules[\\\]react[\\\]dist[\\\].*|website\\node_modules\\.*|heapCapture\\bundle\.js|.*\\__tests__\\.*)$/: Unterminated character class. Run CLI with --verbose flag for more details.

Metro Bundler process exited with code 1
Set EXPO_DEBUG=true in your env to view the stack trace.
error Command failed with exit code 1.
```
my environment:
windows 10
node: 12.11.1
yarn: 1.19.1
npm: 6.11.3
cheers!

**Comment by palingheorghe** [comment]
Hi @pouyamiralayi ! Have you tried running `expo install react-native-svg`?

**Comment by pouyamiralayi** [comment]
@palingheorghe no i will try it tonight!
cheers!

**Comment by pouyamiralayi** [comment]
thanks @palingheorghe this is working now!
one suggestion that might help is to downgrade the ``expo-svg`` package to ``9.9.9`` in the project ``package.json``. this will be compatible with latest ``expo-cli`` ``v35``.
cheers!

**Comment by pouyamiralayi** [comment]
@palingheorghe after above changes, the dashboard shows up fine but it takes about 30 seconds for it to crash again. the cli output is the following:
```
error Invalid regular expression: /(.*\\__fixtures__\\.*|node_modules[\\\]react[\\\]dist[\\\].*|website\\node_modules\\.*|heapCapture\\bundle\.js|.*\\__tests__\\.*)$/: Unterminated character class. Run CLI with --verbose flag for more details.
```
cheers!

**Comment by palingheorghe** [comment]
Glad it worked! Honestly, I don't really get what's going on with your app right now. Could you share more information please? As far as I can see there's a problem with a regular expression but the app is not using anything like that so it must be in the `node_modules` directory. There's a problem with a package but I don't suffer from the same issue so giving more information would be really cool 🧜🏽‍♂️.

**Comment by pouyamiralayi** [comment]
@palingheorghe check this out: [expo regex error and node version](https://github.com/Rocketseat/expo-common-issues/blob/master/README.md#invalid-regular-expression)
my node version is 12+ so that's the reason!
i suggest updating the README in the manner of requirements.
cheers!
**UPDATE**
if anybody is using node 12+ and wants to stay on node 12+, there is an issue with node **12.11** and the fix is described [here](https://stackoverflow.com/questions/58120990/question-getting-error-on-react-native-start/58199866#58199866). 
Now i am using expo on node **v12.11.1** without any problem!
