### ISSUE TITLE
fontFamily "Feather" is not a system font and has not been loaded through Font.loadAsync.

### ISSUE THREAD

**Issue by dhamodar-adappt** [galio-org/galio-starter-kit#18]
fontFamily "Feather" is not a system font and has not been loaded through Font.loadAsync.

**Comment by AndyOsei** [comment]
Galio does not provide any feather font family...
It uses the Icon component to expose the various icon sets provided by react-native-vector-icons and Galio font like this...
```<Icon name='check' family='feather' size={18} color='red' />```

Hence you have to first install react-native-vector-icons as a peer dependency...

**Comment by dhamodar-adappt** [comment]
npm i react-native-fontawesome --save for above solution
