### ISSUE TITLE
Getting Invariant Violation at dashboard and presentation screen

### ISSUE THREAD

**Issue by irishabh96** [galio-org/galio-starter-kit#3]
![Screenshot_20191129-012023_Expo](https://user-images.githubusercontent.com/14240044/69829629-c4fac180-1246-11ea-904d-7cde3a2b1002.jpg)
![Screenshot 2019-11-29 at 1 21 05 AM](https://user-images.githubusercontent.com/14240044/69829639-d47a0a80-1246-11ea-8b71-02c82db71640.png)

**Comment by palingheorghe** [comment]
Accepted for the next version so closing this issue.
