### ISSUE TITLE
tarball issue

### ISSUE THREAD

**Issue by cmdhakar11** [galio-org/galio-starter-kit#6]
npm WARN tarball tarball data for react-native@https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz (sha512-KBH833yTYW/u2E1KKTAq2jYAqZOgXyLwg/TVpG6JbHyTG424f5gF4CB7KUw==) seems to be corrupted. Trying one more time

**Comment by palingheorghe** [comment]
Hi @cmdhakar-001 ! This isn't a problem with our repo. It must probably be a problem with your npm package. You could try re-installing npm on your machine.

**Comment by cmdhakar11** [comment]
yes i got the issue. thanks
