### ISSUE TITLE
If I want to activate the Dashboard Screen, getting errors

### ISSUE THREAD

**Issue by m0shiurX** [galio-org/galio-starter-kit#7]
In route.js
`  Dashboard: {
    screen: Dashboard,
    navigationOptions: {
      drawerLabel: 'Dashboard screen',
      drawerIcon: props => <MenuIcon name="flag" family="font-awesome" focused={props.focused} />,
    },
  },`
If I uncomment this the dashboard.js (component) lodign with error: Invariant Violation: Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `Dashboard`.

This error is located at:
    in RCTView (at View.js:45)
    in View (at Block.js:58)
    in Block (at theme/index.js:33)
    in _class (at Dashboard.js:124)
    in RCTView (at View.js:45)
    in View (at ScrollView.js:976)
    in RCTScrollView (at ScrollView.js:1115)
    in ScrollView (at Dashboard.js:162)
    in RCTView (at View.js:45)
    in View (at SafeAreaView.js:37)
    in SafeAreaView (at Block.js:51)
    in Block (at theme/index.js:33)
    in _class (at Dashboard.js:154)
    in Dashboard (at SceneView.js:9)
    in SceneView (at DrawerView.js:87)
    in RCTView (at View.js:45)
    in View (at DrawerLayoutAndroid.android.js:198)
    in AndroidDrawerLayout (at DrawerLayoutAndroid.android.js:217)
    in DrawerLayoutAndroid (at DrawerView.js:84)
    in DrawerView (at createNavigator.js:57)
    in Navigator (at createNavigationContainer.js:376)
    in NavigationContainer (at App.js:10)
    in RCTView (at View.js:45)
    in View (at App.js:8)
    in App (at withExpoRoot.js:20)
    in RootErrorBoundary (at withExpoRoot.js:19)
    in ExpoRootComponent (at renderApplication.js:35)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:98)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:115)
    in AppContainer (at renderApplication.js:34)

This error is located at:
    in NavigationContainer (at App.js:10)
    in RCTView (at View.js:45)
    in View (at App.js:8)
    in App (at withExpoRoot.js:20)
    in RootErrorBoundary (at withExpoRoot.js:19)
    in ExpoRootComponent (at renderApplication.js:35)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:98)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:115)
    in AppContainer (at renderApplication.js:34)

**Comment by jacksontong** [comment]
same for me

**Comment by m0shiurX** [comment]
> same for me

see the other brunch, there's a working solution there.

**Comment by kirame09** [comment]
up

**Comment by palingheorghe** [comment]
@unimrgm is right! There is a working solution on the `dev` branch. Please use that one if you need to check out the Dashboard screen.
